/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
//Macros definition
#define RCC_Base 0x40023800  // using because it is the base address of the RCC register and enable GPIOA clock it get form the datasheet
#define GPIOA_Base 0x40020000 //using because it is the base address of the GPIOA register and enable GPIOA clock it get form the datasheet

//define pointers
uint32_t *AHB1ENR = (uint32_t *)(RCC_Base + 0x30); //enable GPIOA clock
uint32_t *GPIOA_Moder = (uint32_t *)(GPIOA_Base + 0x00); // configure GPIOA mode
uint32_t *GPIOA_ODR = (uint32_t *)(GPIOA_Base + 0x14); // configure GPIOA output data register

//functions prototypes
void GPIOA_Init(); // this function is used to initialize GPIOA
void delay(); // this function is used to delay the program execution

int main(void)
{


    GPIOA_Init();

    /* Loop forever */
    while (1)
    {
        *GPIOA_ODR |= (1 << 5);   // toggle PA5
        delay();

        *GPIOA_ODR &= ~(1 << 5);
        delay();
    }
}
// GPIOA initialization

    void GPIOA_Init()
    {

        *AHB1ENR |= (1 << 0); //enable GPIOA clock
        *GPIOA_Moder |= (1 << 10); // set bit no. 10 of GPIOA mode register to configure GPIOA pin 5 as output
        *GPIOA_Moder &= ~(1 << 11); // set bit no. 11 of GPIOA mode register to configure GPIOA pin 5 as output

    }

    //software delay function
    void delay()
    {
        int loop_cnt;
        for(loop_cnt = 0; loop_cnt < 1000000; loop_cnt++);
    }
