/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4xx.h>
#include <core_cm4.h>

#define INPUT  1
#define OUTPUT 0

void GPIO_init(GPIO_TypeDef *GPIO, uint8_t PIN_No, uint8_t MODE);

int main(void)
{
    GPIO_init(GPIOA, 5, OUTPUT);
    GPIO_init(GPIOC, 13, INPUT);

    NVIC_EnableIRQ(EXTI15_10_IRQn);
    NVIC_SetPriority(EXTI15_10_IRQn, 1);

    SYSCFG->EXTICR[3] |= (1 << 5);
    EXTI->RTSR |= (1 << 13);
    EXTI->IMR  |= (1 << 13);

    while (1);
}

void GPIO_init(GPIO_TypeDef *GPIO, uint8_t PIN_No, uint8_t MODE)
{
    RCC->AHB1ENR |= (1 << 0) | (1 << 2);
    RCC->APB2ENR |= (1 << 14);

    if (MODE == INPUT)
    {
        GPIO->MODER &= ~(3 << (PIN_No * 2));
    }
    else
    {
        GPIO->MODER &= ~(3 << (PIN_No * 2));
        GPIO->MODER |=  (1 << (PIN_No * 2));
    }
}

void EXTI15_10_IRQHandler(void)
{
    if (EXTI->PR & (1 << 13))
    {
        GPIOA->ODR ^= (1 << 5);
        for (int j = 0; j < 100000; j++);
        EXTI->PR |= (1 << 13);
    }
}
