/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"

void GPIO_init();
void Timer_init();
void Timer_delay();
uint8_t mode=0;

int main(void)
{
	GPIO_init();
	Timer_init();
	TIM2->CR1 |= (1 << 0);
	while(1)
	{

		if (!(GPIOC->IDR & (1 << 13)))// Button pressed
		{
			while(!(GPIOC->IDR & (1 << 13)));
			//Toggle mode
			if (mode==1)
			{
				mode=0;
			}
			else
			{
				mode = 1;
			}
		}
		GPIOA->ODR ^= (1 << 5);
		if (mode == 0)
		{
			Timer_delay();
			Timer_delay();
		}
		else
		{
			Timer_delay();
		}
	}
}

/* GPIO Intialisation */
void GPIO_init(void)
{
	RCC->AHB1ENR |= (1<<0);//LED GPIOA
	RCC->AHB1ENR |= (1<<2);//PUSH BTN GPIOC
	GPIOA->MODER &= ~(3 << 10);//PA5
	GPIOA->MODER |=  (1 << 10);//PA5
	GPIOC->MODER &= ~(3 << 26);//PA13
}

/* Timer Intialisation */
void Timer_init(void)
{
    RCC->APB1ENR |= (1 << 0);   // Enable TIM2 clock

    TIM2->PSC = 16000;
    TIM2->ARR = 250 - 1;    // 250 ms delay
    TIM2->CNT = 0;
}

void Timer_delay(void)
{
    TIM2->CNT = 0;
    while (!(TIM2->SR & 1)) {}
    TIM2->SR &= ~1;
}
